// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PasTech.SmartHome.API.Data;

#nullable disable

namespace PasTech.SmartHome.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260622165633_PasSmartHomeInit")]
    partial class PasSmartHomeInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PasTech.SmartHome.API.Models.Automation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConditionConfig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastTriggeredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TriggerConfig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TriggerCount")
                        .HasColumnType("int");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Automations");
                });

            modelBuilder.Entity("PasTech.SmartHome.API.Models.AutomationAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionConfig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AutomationId")
                        .HasColumnType("int");

                    b.Property<int>("DelaySeconds")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("TargetDeviceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AutomationId");

                    b.HasIndex("TargetDeviceId");

                    b.ToTable("AutomationActions");
                });

            modelBuilder.Entity("PasTech.SmartHome.API.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MacAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MqttTopic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Generic",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsOnline = true,
                            MqttTopic = "pas/devices/1/state",
                            Name = "ไฟห้องนั่งเล่น",
                            RoomId = 1,
                            Type = "Light"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Generic",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsOnline = true,
                            MqttTopic = "pas/devices/2/state",
                            Name = "ไฟห้องนอน",
                            RoomId = 2,
                            Type = "Light"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Generic",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsOnline = true,
                            MqttTopic = "pas/devices/3/state",
                            Name = "ไฟห้องครัว",
                            RoomId = 3,
                            Type = "Light"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Generic",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsOnline = true,
                            MqttTopic = "pas/devices/4/state",
                            Name = "ไฟห้องทำงาน",
                            RoomId = 5,
                            Type = "Light"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Daikin",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsOnline = true,
                            MqttTopic = "pas/devices/5/state",
                            Name = "แอร์ห้องนั่งเล่น",
                            RoomId = 1,
                            Type = "AC"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Mitsubishi",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsOnline = true,
                            MqttTopic = "pas/devices/6/state",
                            Name = "แอร์ห้องนอน",
                            RoomId = 2,
                            Type = "AC"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "LG",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsOnline = true,
                            MqttTopic = "pas/devices/7/state",
                            Name = "แอร์ห้องทำงาน",
                            RoomId = 5,
                            Type = "AC"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Generic",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsOnline = true,
                            MqttTopic = "pas/devices/8/state",
                            Name = "ประตูหน้าบ้าน",
                            RoomId = 1,
                            Type = "Door"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Generic",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsOnline = true,
                            MqttTopic = "pas/devices/9/state",
                            Name = "ประตูโรงรถ",
                            RoomId = 7,
                            Type = "Door"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Generic",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsOnline = true,
                            MqttTopic = "pas/devices/10/state",
                            Name = "ประตูหลัง",
                            RoomId = 8,
                            Type = "Door"
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Generic",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsOnline = true,
                            MqttTopic = "pas/devices/11/state",
                            Name = "กล้องหน้าบ้าน",
                            RoomId = 1,
                            Type = "Camera"
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Generic",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsOnline = true,
                            MqttTopic = "pas/devices/12/state",
                            Name = "กล้องสวนหลัง",
                            RoomId = 8,
                            Type = "Camera"
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Generic",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsOnline = true,
                            MqttTopic = "pas/devices/13/state",
                            Name = "กล้องโรงรถ",
                            RoomId = 7,
                            Type = "Camera"
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Generic",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsOnline = true,
                            MqttTopic = "pas/devices/14/state",
                            Name = "กล้องห้องนั่งเล่น",
                            RoomId = 1,
                            Type = "Camera"
                        });
                });

            modelBuilder.Entity("PasTech.SmartHome.API.Models.DeviceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("UserId");

                    b.ToTable("DeviceLogs");
                });

            modelBuilder.Entity("PasTech.SmartHome.API.Models.DeviceState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccessMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Brightness")
                        .HasColumnType("float");

                    b.Property<int>("ColorB")
                        .HasColumnType("int");

                    b.Property<int>("ColorG")
                        .HasColumnType("int");

                    b.Property<int>("ColorR")
                        .HasColumnType("int");

                    b.Property<int>("ColorTemp")
                        .HasColumnType("int");

                    b.Property<double>("Current")
                        .HasColumnType("float");

                    b.Property<double>("CurrentTemperature")
                        .HasColumnType("float");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int>("FanSpeed")
                        .HasColumnType("int");

                    b.Property<bool>("HasMotion")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNightVision")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOn")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecording")
                        .HasColumnType("bit");

                    b.Property<string>("LastAccessBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PowerWatts")
                        .HasColumnType("float");

                    b.Property<double>("SetTemperature")
                        .HasColumnType("float");

                    b.Property<string>("SnapshotUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreamUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SwingMode")
                        .HasColumnType("bit");

                    b.Property<int>("TimerMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Voltage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("DeviceStates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcMode = "cool",
                            Brightness = 0.80000000000000004,
                            ColorB = 255,
                            ColorG = 255,
                            ColorR = 255,
                            ColorTemp = 4000,
                            Current = 0.0,
                            CurrentTemperature = 28.0,
                            DeviceId = 1,
                            FanSpeed = 2,
                            HasMotion = false,
                            IsLocked = true,
                            IsNightVision = false,
                            IsOn = true,
                            IsRecording = false,
                            PowerWatts = 0.0,
                            SetTemperature = 25.0,
                            SwingMode = false,
                            TimerMinutes = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Voltage = 0.0
                        },
                        new
                        {
                            Id = 2,
                            AcMode = "cool",
                            Brightness = 1.0,
                            ColorB = 255,
                            ColorG = 255,
                            ColorR = 255,
                            ColorTemp = 4000,
                            Current = 0.0,
                            CurrentTemperature = 28.0,
                            DeviceId = 2,
                            FanSpeed = 2,
                            HasMotion = false,
                            IsLocked = true,
                            IsNightVision = false,
                            IsOn = false,
                            IsRecording = false,
                            PowerWatts = 0.0,
                            SetTemperature = 25.0,
                            SwingMode = false,
                            TimerMinutes = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Voltage = 0.0
                        },
                        new
                        {
                            Id = 3,
                            AcMode = "cool",
                            Brightness = 0.59999999999999998,
                            ColorB = 255,
                            ColorG = 255,
                            ColorR = 255,
                            ColorTemp = 4000,
                            Current = 0.0,
                            CurrentTemperature = 28.0,
                            DeviceId = 3,
                            FanSpeed = 2,
                            HasMotion = false,
                            IsLocked = true,
                            IsNightVision = false,
                            IsOn = true,
                            IsRecording = false,
                            PowerWatts = 0.0,
                            SetTemperature = 25.0,
                            SwingMode = false,
                            TimerMinutes = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Voltage = 0.0
                        },
                        new
                        {
                            Id = 4,
                            AcMode = "cool",
                            Brightness = 0.90000000000000002,
                            ColorB = 255,
                            ColorG = 255,
                            ColorR = 255,
                            ColorTemp = 4000,
                            Current = 0.0,
                            CurrentTemperature = 28.0,
                            DeviceId = 4,
                            FanSpeed = 2,
                            HasMotion = false,
                            IsLocked = true,
                            IsNightVision = false,
                            IsOn = true,
                            IsRecording = false,
                            PowerWatts = 0.0,
                            SetTemperature = 25.0,
                            SwingMode = false,
                            TimerMinutes = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Voltage = 0.0
                        },
                        new
                        {
                            Id = 5,
                            AcMode = "cool",
                            Brightness = 1.0,
                            ColorB = 255,
                            ColorG = 255,
                            ColorR = 255,
                            ColorTemp = 4000,
                            Current = 0.0,
                            CurrentTemperature = 26.0,
                            DeviceId = 5,
                            FanSpeed = 2,
                            HasMotion = false,
                            IsLocked = true,
                            IsNightVision = false,
                            IsOn = true,
                            IsRecording = false,
                            PowerWatts = 0.0,
                            SetTemperature = 24.0,
                            SwingMode = false,
                            TimerMinutes = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Voltage = 0.0
                        },
                        new
                        {
                            Id = 6,
                            AcMode = "cool",
                            Brightness = 1.0,
                            ColorB = 255,
                            ColorG = 255,
                            ColorR = 255,
                            ColorTemp = 4000,
                            Current = 0.0,
                            CurrentTemperature = 28.0,
                            DeviceId = 6,
                            FanSpeed = 1,
                            HasMotion = false,
                            IsLocked = true,
                            IsNightVision = false,
                            IsOn = false,
                            IsRecording = false,
                            PowerWatts = 0.0,
                            SetTemperature = 25.0,
                            SwingMode = false,
                            TimerMinutes = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Voltage = 0.0
                        },
                        new
                        {
                            Id = 7,
                            AcMode = "cool",
                            Brightness = 1.0,
                            ColorB = 255,
                            ColorG = 255,
                            ColorR = 255,
                            ColorTemp = 4000,
                            Current = 0.0,
                            CurrentTemperature = 27.0,
                            DeviceId = 7,
                            FanSpeed = 3,
                            HasMotion = false,
                            IsLocked = true,
                            IsNightVision = false,
                            IsOn = true,
                            IsRecording = false,
                            PowerWatts = 0.0,
                            SetTemperature = 23.0,
                            SwingMode = false,
                            TimerMinutes = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Voltage = 0.0
                        },
                        new
                        {
                            Id = 8,
                            AcMode = "cool",
                            Brightness = 1.0,
                            ColorB = 255,
                            ColorG = 255,
                            ColorR = 255,
                            ColorTemp = 4000,
                            Current = 0.0,
                            CurrentTemperature = 28.0,
                            DeviceId = 8,
                            FanSpeed = 2,
                            HasMotion = false,
                            IsLocked = true,
                            IsNightVision = false,
                            IsOn = false,
                            IsRecording = false,
                            PowerWatts = 0.0,
                            SetTemperature = 25.0,
                            SwingMode = false,
                            TimerMinutes = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Voltage = 0.0
                        },
                        new
                        {
                            Id = 9,
                            AcMode = "cool",
                            Brightness = 1.0,
                            ColorB = 255,
                            ColorG = 255,
                            ColorR = 255,
                            ColorTemp = 4000,
                            Current = 0.0,
                            CurrentTemperature = 28.0,
                            DeviceId = 9,
                            FanSpeed = 2,
                            HasMotion = false,
                            IsLocked = false,
                            IsNightVision = false,
                            IsOn = false,
                            IsRecording = false,
                            PowerWatts = 0.0,
                            SetTemperature = 25.0,
                            SwingMode = false,
                            TimerMinutes = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Voltage = 0.0
                        },
                        new
                        {
                            Id = 10,
                            AcMode = "cool",
                            Brightness = 1.0,
                            ColorB = 255,
                            ColorG = 255,
                            ColorR = 255,
                            ColorTemp = 4000,
                            Current = 0.0,
                            CurrentTemperature = 28.0,
                            DeviceId = 10,
                            FanSpeed = 2,
                            HasMotion = false,
                            IsLocked = true,
                            IsNightVision = false,
                            IsOn = false,
                            IsRecording = false,
                            PowerWatts = 0.0,
                            SetTemperature = 25.0,
                            SwingMode = false,
                            TimerMinutes = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Voltage = 0.0
                        },
                        new
                        {
                            Id = 11,
                            AcMode = "cool",
                            Brightness = 1.0,
                            ColorB = 255,
                            ColorG = 255,
                            ColorR = 255,
                            ColorTemp = 4000,
                            Current = 0.0,
                            CurrentTemperature = 28.0,
                            DeviceId = 11,
                            FanSpeed = 2,
                            HasMotion = true,
                            IsLocked = true,
                            IsNightVision = false,
                            IsOn = false,
                            IsRecording = true,
                            PowerWatts = 0.0,
                            SetTemperature = 25.0,
                            SwingMode = false,
                            TimerMinutes = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Voltage = 0.0
                        },
                        new
                        {
                            Id = 12,
                            AcMode = "cool",
                            Brightness = 1.0,
                            ColorB = 255,
                            ColorG = 255,
                            ColorR = 255,
                            ColorTemp = 4000,
                            Current = 0.0,
                            CurrentTemperature = 28.0,
                            DeviceId = 12,
                            FanSpeed = 2,
                            HasMotion = false,
                            IsLocked = true,
                            IsNightVision = true,
                            IsOn = false,
                            IsRecording = true,
                            PowerWatts = 0.0,
                            SetTemperature = 25.0,
                            SwingMode = false,
                            TimerMinutes = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Voltage = 0.0
                        },
                        new
                        {
                            Id = 13,
                            AcMode = "cool",
                            Brightness = 1.0,
                            ColorB = 255,
                            ColorG = 255,
                            ColorR = 255,
                            ColorTemp = 4000,
                            Current = 0.0,
                            CurrentTemperature = 28.0,
                            DeviceId = 13,
                            FanSpeed = 2,
                            HasMotion = false,
                            IsLocked = true,
                            IsNightVision = false,
                            IsOn = false,
                            IsRecording = true,
                            PowerWatts = 0.0,
                            SetTemperature = 25.0,
                            SwingMode = false,
                            TimerMinutes = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Voltage = 0.0
                        },
                        new
                        {
                            Id = 14,
                            AcMode = "cool",
                            Brightness = 1.0,
                            ColorB = 255,
                            ColorG = 255,
                            ColorR = 255,
                            ColorTemp = 4000,
                            Current = 0.0,
                            CurrentTemperature = 28.0,
                            DeviceId = 14,
                            FanSpeed = 2,
                            HasMotion = false,
                            IsLocked = true,
                            IsNightVision = true,
                            IsOn = false,
                            IsRecording = true,
                            PowerWatts = 0.0,
                            SetTemperature = 25.0,
                            SwingMode = false,
                            TimerMinutes = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Voltage = 0.0
                        });
                });

            modelBuilder.Entity("PasTech.SmartHome.API.Models.EnergyUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CostBaht")
                        .HasColumnType("float");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<double>("KiloWattHours")
                        .HasColumnType("float");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("EnergyUsages");
                });

            modelBuilder.Entity("PasTech.SmartHome.API.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RelatedDeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("PasTech.SmartHome.API.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("PasTech.SmartHome.API.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<double?>("FloorPlanX")
                        .HasColumnType("float");

                    b.Property<double?>("FloorPlanY")
                        .HasColumnType("float");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            Icon = "🛋️",
                            Name = "ห้องนั่งเล่น"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            Icon = "🛏️",
                            Name = "ห้องนอนหลัก"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            Icon = "🍳",
                            Name = "ห้องครัว"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            Icon = "🚿",
                            Name = "ห้องน้ำ"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            Icon = "💼",
                            Name = "ห้องทำงาน"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            Icon = "🧸",
                            Name = "ห้องนอนลูก"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 0,
                            Icon = "🚗",
                            Name = "โรงรถ"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 0,
                            Icon = "🌿",
                            Name = "สวน"
                        });
                });

            modelBuilder.Entity("PasTech.SmartHome.API.Models.Scene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastActivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Scenes");
                });

            modelBuilder.Entity("PasTech.SmartHome.API.Models.SecurityEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AcknowledgedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("SecurityEvents");
                });

            modelBuilder.Entity("PasTech.SmartHome.API.Models.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastReadingAt")
                        .HasColumnType("datetime2");

                    b.Property<double?>("LastValue")
                        .HasColumnType("float");

                    b.Property<string>("MqttTopic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Sensors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsOnline = true,
                            LastReadingAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastValue = 26.5,
                            MqttTopic = "pas/sensors/1",
                            Name = "อุณหภูมิห้องนั่งเล่น",
                            RoomId = 1,
                            Type = "Temperature",
                            Unit = "°C"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsOnline = true,
                            LastReadingAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastValue = 62.0,
                            MqttTopic = "pas/sensors/2",
                            Name = "ความชื้นห้องนั่งเล่น",
                            RoomId = 1,
                            Type = "Humidity",
                            Unit = "%"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsOnline = true,
                            LastReadingAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastValue = 0.0,
                            MqttTopic = "pas/sensors/3",
                            Name = "เซนเซอร์การเคลื่อนไหว",
                            RoomId = 1,
                            Type = "Motion",
                            Unit = ""
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsOnline = true,
                            LastReadingAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastValue = 0.0,
                            MqttTopic = "pas/sensors/4",
                            Name = "เซนเซอร์ควัน",
                            RoomId = 3,
                            Type = "Smoke",
                            Unit = "ppm"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsOnline = true,
                            LastReadingAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastValue = 0.0,
                            MqttTopic = "pas/sensors/5",
                            Name = "เซนเซอร์น้ำรั่ว",
                            RoomId = 4,
                            Type = "WaterLeak",
                            Unit = ""
                        });
                });

            modelBuilder.Entity("PasTech.SmartHome.API.Models.SensorReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SensorId")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SensorId");

                    b.ToTable("SensorReadings");
                });

            modelBuilder.Entity("PasTech.SmartHome.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PasTech.SmartHome.API.Models.AutomationAction", b =>
                {
                    b.HasOne("PasTech.SmartHome.API.Models.Automation", "Automation")
                        .WithMany("Actions")
                        .HasForeignKey("AutomationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PasTech.SmartHome.API.Models.Device", "TargetDevice")
                        .WithMany()
                        .HasForeignKey("TargetDeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Automation");

                    b.Navigation("TargetDevice");
                });

            modelBuilder.Entity("PasTech.SmartHome.API.Models.Device", b =>
                {
                    b.HasOne("PasTech.SmartHome.API.Models.Room", "Room")
                        .WithMany("Devices")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("PasTech.SmartHome.API.Models.DeviceLog", b =>
                {
                    b.HasOne("PasTech.SmartHome.API.Models.Device", "Device")
                        .WithMany("Logs")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PasTech.SmartHome.API.Models.User", "User")
                        .WithMany("DeviceLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Device");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PasTech.SmartHome.API.Models.DeviceState", b =>
                {
                    b.HasOne("PasTech.SmartHome.API.Models.Device", "Device")
                        .WithOne("State")
                        .HasForeignKey("PasTech.SmartHome.API.Models.DeviceState", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("PasTech.SmartHome.API.Models.EnergyUsage", b =>
                {
                    b.HasOne("PasTech.SmartHome.API.Models.Device", "Device")
                        .WithMany("EnergyUsages")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("PasTech.SmartHome.API.Models.Notification", b =>
                {
                    b.HasOne("PasTech.SmartHome.API.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PasTech.SmartHome.API.Models.RefreshToken", b =>
                {
                    b.HasOne("PasTech.SmartHome.API.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PasTech.SmartHome.API.Models.SecurityEvent", b =>
                {
                    b.HasOne("PasTech.SmartHome.API.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("PasTech.SmartHome.API.Models.Sensor", b =>
                {
                    b.HasOne("PasTech.SmartHome.API.Models.Room", "Room")
                        .WithMany("Sensors")
                        .HasForeignKey("RoomId");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("PasTech.SmartHome.API.Models.SensorReading", b =>
                {
                    b.HasOne("PasTech.SmartHome.API.Models.Sensor", "Sensor")
                        .WithMany("Readings")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("PasTech.SmartHome.API.Models.Automation", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("PasTech.SmartHome.API.Models.Device", b =>
                {
                    b.Navigation("EnergyUsages");

                    b.Navigation("Logs");

                    b.Navigation("State");
                });

            modelBuilder.Entity("PasTech.SmartHome.API.Models.Room", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("PasTech.SmartHome.API.Models.Sensor", b =>
                {
                    b.Navigation("Readings");
                });

            modelBuilder.Entity("PasTech.SmartHome.API.Models.User", b =>
                {
                    b.Navigation("DeviceLogs");

                    b.Navigation("Notifications");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
