// <auto-generated />
using System;
using LumiHome.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LumiHome.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LumiHome.API.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 123, DateTimeKind.Utc).AddTicks(8753),
                            IsOnline = true,
                            Name = "ไฟเพดาน",
                            RoomId = 1,
                            Type = "Light"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 124, DateTimeKind.Utc).AddTicks(815),
                            IsOnline = true,
                            Name = "ไฟอ่านหนังสือ",
                            RoomId = 1,
                            Type = "Light"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 124, DateTimeKind.Utc).AddTicks(819),
                            IsOnline = true,
                            Name = "ไฟเพดาน",
                            RoomId = 2,
                            Type = "Light"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 124, DateTimeKind.Utc).AddTicks(821),
                            IsOnline = true,
                            Name = "ไฟหัวเตียง",
                            RoomId = 2,
                            Type = "Light"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 124, DateTimeKind.Utc).AddTicks(823),
                            IsOnline = true,
                            Name = "แอร์",
                            RoomId = 1,
                            Type = "AC"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 124, DateTimeKind.Utc).AddTicks(824),
                            IsOnline = true,
                            Name = "แอร์",
                            RoomId = 2,
                            Type = "AC"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 124, DateTimeKind.Utc).AddTicks(827),
                            IsOnline = true,
                            Name = "แอร์",
                            RoomId = 5,
                            Type = "AC"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 124, DateTimeKind.Utc).AddTicks(828),
                            IsOnline = true,
                            Name = "แอร์",
                            RoomId = 6,
                            Type = "AC"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 124, DateTimeKind.Utc).AddTicks(829),
                            IsOnline = true,
                            Name = "ประตูหน้า",
                            RoomId = 1,
                            Type = "Door"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 124, DateTimeKind.Utc).AddTicks(831),
                            IsOnline = true,
                            Name = "ประตูหลัง",
                            RoomId = 1,
                            Type = "Door"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 124, DateTimeKind.Utc).AddTicks(832),
                            IsOnline = true,
                            Name = "ประตูโรงรถ",
                            RoomId = 7,
                            Type = "Door"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 124, DateTimeKind.Utc).AddTicks(834),
                            IsOnline = true,
                            Name = "ประตูห้องนอน",
                            RoomId = 2,
                            Type = "Door"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 124, DateTimeKind.Utc).AddTicks(835),
                            IsOnline = true,
                            Name = "กล้องหน้าบ้าน",
                            RoomId = 1,
                            Type = "Camera"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 124, DateTimeKind.Utc).AddTicks(837),
                            IsOnline = true,
                            Name = "กล้องห้องนั่งเล่น",
                            RoomId = 1,
                            Type = "Camera"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 124, DateTimeKind.Utc).AddTicks(838),
                            IsOnline = true,
                            Name = "กล้องสวน",
                            RoomId = 8,
                            Type = "Camera"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 124, DateTimeKind.Utc).AddTicks(840),
                            IsOnline = true,
                            Name = "กล้องโรงรถ",
                            RoomId = 7,
                            Type = "Camera"
                        });
                });

            modelBuilder.Entity("LumiHome.API.Models.DeviceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("DeviceLogs");
                });

            modelBuilder.Entity("LumiHome.API.Models.DeviceState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Brightness")
                        .HasColumnType("float");

                    b.Property<double>("CurrentTemperature")
                        .HasColumnType("float");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int>("FanSpeed")
                        .HasColumnType("int");

                    b.Property<bool>("HasMotion")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNightVision")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOn")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecording")
                        .HasColumnType("bit");

                    b.Property<double>("SetTemperature")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("DeviceStates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcMode = "cool",
                            Brightness = 0.80000000000000004,
                            CurrentTemperature = 28.0,
                            DeviceId = 1,
                            FanSpeed = 2,
                            HasMotion = false,
                            IsLocked = true,
                            IsNightVision = false,
                            IsOn = true,
                            IsRecording = false,
                            SetTemperature = 25.0,
                            UpdatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 124, DateTimeKind.Utc).AddTicks(2241)
                        },
                        new
                        {
                            Id = 2,
                            AcMode = "cool",
                            Brightness = 0.5,
                            CurrentTemperature = 28.0,
                            DeviceId = 2,
                            FanSpeed = 2,
                            HasMotion = false,
                            IsLocked = true,
                            IsNightVision = false,
                            IsOn = false,
                            IsRecording = false,
                            SetTemperature = 25.0,
                            UpdatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 124, DateTimeKind.Utc).AddTicks(3615)
                        },
                        new
                        {
                            Id = 3,
                            AcMode = "cool",
                            Brightness = 0.59999999999999998,
                            CurrentTemperature = 28.0,
                            DeviceId = 3,
                            FanSpeed = 2,
                            HasMotion = false,
                            IsLocked = true,
                            IsNightVision = false,
                            IsOn = true,
                            IsRecording = false,
                            SetTemperature = 25.0,
                            UpdatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 124, DateTimeKind.Utc).AddTicks(3616)
                        },
                        new
                        {
                            Id = 4,
                            AcMode = "cool",
                            Brightness = 0.29999999999999999,
                            CurrentTemperature = 28.0,
                            DeviceId = 4,
                            FanSpeed = 2,
                            HasMotion = false,
                            IsLocked = true,
                            IsNightVision = false,
                            IsOn = true,
                            IsRecording = false,
                            SetTemperature = 25.0,
                            UpdatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 124, DateTimeKind.Utc).AddTicks(3618)
                        },
                        new
                        {
                            Id = 5,
                            AcMode = "cool",
                            Brightness = 1.0,
                            CurrentTemperature = 26.0,
                            DeviceId = 5,
                            FanSpeed = 2,
                            HasMotion = false,
                            IsLocked = true,
                            IsNightVision = false,
                            IsOn = true,
                            IsRecording = false,
                            SetTemperature = 24.0,
                            UpdatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 124, DateTimeKind.Utc).AddTicks(3621)
                        },
                        new
                        {
                            Id = 6,
                            AcMode = "cool",
                            Brightness = 1.0,
                            CurrentTemperature = 27.0,
                            DeviceId = 6,
                            FanSpeed = 1,
                            HasMotion = false,
                            IsLocked = true,
                            IsNightVision = false,
                            IsOn = true,
                            IsRecording = false,
                            SetTemperature = 25.0,
                            UpdatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 124, DateTimeKind.Utc).AddTicks(4895)
                        },
                        new
                        {
                            Id = 7,
                            AcMode = "cool",
                            Brightness = 1.0,
                            CurrentTemperature = 30.0,
                            DeviceId = 7,
                            FanSpeed = 2,
                            HasMotion = false,
                            IsLocked = true,
                            IsNightVision = false,
                            IsOn = false,
                            IsRecording = false,
                            SetTemperature = 26.0,
                            UpdatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 124, DateTimeKind.Utc).AddTicks(4898)
                        },
                        new
                        {
                            Id = 8,
                            AcMode = "cool",
                            Brightness = 1.0,
                            CurrentTemperature = 28.0,
                            DeviceId = 8,
                            FanSpeed = 2,
                            HasMotion = false,
                            IsLocked = true,
                            IsNightVision = false,
                            IsOn = false,
                            IsRecording = false,
                            SetTemperature = 26.0,
                            UpdatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 124, DateTimeKind.Utc).AddTicks(4899)
                        },
                        new
                        {
                            Id = 9,
                            AcMode = "cool",
                            Brightness = 1.0,
                            CurrentTemperature = 28.0,
                            DeviceId = 9,
                            FanSpeed = 2,
                            HasMotion = false,
                            IsLocked = true,
                            IsNightVision = false,
                            IsOn = true,
                            IsRecording = false,
                            SetTemperature = 25.0,
                            UpdatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 124, DateTimeKind.Utc).AddTicks(4901)
                        },
                        new
                        {
                            Id = 10,
                            AcMode = "cool",
                            Brightness = 1.0,
                            CurrentTemperature = 28.0,
                            DeviceId = 10,
                            FanSpeed = 2,
                            HasMotion = false,
                            IsLocked = true,
                            IsNightVision = false,
                            IsOn = true,
                            IsRecording = false,
                            SetTemperature = 25.0,
                            UpdatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 124, DateTimeKind.Utc).AddTicks(5187)
                        },
                        new
                        {
                            Id = 11,
                            AcMode = "cool",
                            Brightness = 1.0,
                            CurrentTemperature = 28.0,
                            DeviceId = 11,
                            FanSpeed = 2,
                            HasMotion = false,
                            IsLocked = false,
                            IsNightVision = false,
                            IsOn = true,
                            IsRecording = false,
                            SetTemperature = 25.0,
                            UpdatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 124, DateTimeKind.Utc).AddTicks(5188)
                        },
                        new
                        {
                            Id = 12,
                            AcMode = "cool",
                            Brightness = 1.0,
                            CurrentTemperature = 28.0,
                            DeviceId = 12,
                            FanSpeed = 2,
                            HasMotion = false,
                            IsLocked = true,
                            IsNightVision = false,
                            IsOn = true,
                            IsRecording = false,
                            SetTemperature = 25.0,
                            UpdatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 124, DateTimeKind.Utc).AddTicks(5189)
                        },
                        new
                        {
                            Id = 13,
                            AcMode = "cool",
                            Brightness = 1.0,
                            CurrentTemperature = 28.0,
                            DeviceId = 13,
                            FanSpeed = 2,
                            HasMotion = true,
                            IsLocked = true,
                            IsNightVision = false,
                            IsOn = true,
                            IsRecording = true,
                            SetTemperature = 25.0,
                            UpdatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 124, DateTimeKind.Utc).AddTicks(5190)
                        },
                        new
                        {
                            Id = 14,
                            AcMode = "cool",
                            Brightness = 1.0,
                            CurrentTemperature = 28.0,
                            DeviceId = 14,
                            FanSpeed = 2,
                            HasMotion = false,
                            IsLocked = true,
                            IsNightVision = false,
                            IsOn = true,
                            IsRecording = true,
                            SetTemperature = 25.0,
                            UpdatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 124, DateTimeKind.Utc).AddTicks(5971)
                        },
                        new
                        {
                            Id = 15,
                            AcMode = "cool",
                            Brightness = 1.0,
                            CurrentTemperature = 28.0,
                            DeviceId = 15,
                            FanSpeed = 2,
                            HasMotion = false,
                            IsLocked = true,
                            IsNightVision = true,
                            IsOn = true,
                            IsRecording = true,
                            SetTemperature = 25.0,
                            UpdatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 124, DateTimeKind.Utc).AddTicks(5973)
                        },
                        new
                        {
                            Id = 16,
                            AcMode = "cool",
                            Brightness = 1.0,
                            CurrentTemperature = 28.0,
                            DeviceId = 16,
                            FanSpeed = 2,
                            HasMotion = false,
                            IsLocked = true,
                            IsNightVision = false,
                            IsOn = true,
                            IsRecording = true,
                            SetTemperature = 25.0,
                            UpdatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 124, DateTimeKind.Utc).AddTicks(6467)
                        });
                });

            modelBuilder.Entity("LumiHome.API.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 122, DateTimeKind.Utc).AddTicks(7465),
                            Floor = 1,
                            Icon = "🛋️",
                            Name = "ห้องนั่งเล่น"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 122, DateTimeKind.Utc).AddTicks(9189),
                            Floor = 2,
                            Icon = "🛏️",
                            Name = "ห้องนอนหลัก"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 122, DateTimeKind.Utc).AddTicks(9193),
                            Floor = 1,
                            Icon = "🍳",
                            Name = "ห้องครัว"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 122, DateTimeKind.Utc).AddTicks(9194),
                            Floor = 1,
                            Icon = "🚿",
                            Name = "ห้องน้ำ"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 122, DateTimeKind.Utc).AddTicks(9196),
                            Floor = 2,
                            Icon = "💻",
                            Name = "ห้องทำงาน"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 122, DateTimeKind.Utc).AddTicks(9232),
                            Floor = 2,
                            Icon = "🧸",
                            Name = "ห้องนอนลูก"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 122, DateTimeKind.Utc).AddTicks(9233),
                            Floor = 0,
                            Icon = "🚗",
                            Name = "โรงรถ"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 6, 22, 15, 21, 27, 122, DateTimeKind.Utc).AddTicks(9235),
                            Floor = 0,
                            Icon = "🌿",
                            Name = "สวน"
                        });
                });

            modelBuilder.Entity("LumiHome.API.Models.SecurityEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("SecurityEvents");
                });

            modelBuilder.Entity("LumiHome.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LumiHome.API.Models.Device", b =>
                {
                    b.HasOne("LumiHome.API.Models.Room", "Room")
                        .WithMany("Devices")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("LumiHome.API.Models.DeviceLog", b =>
                {
                    b.HasOne("LumiHome.API.Models.Device", "Device")
                        .WithMany("Logs")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("LumiHome.API.Models.DeviceState", b =>
                {
                    b.HasOne("LumiHome.API.Models.Device", "Device")
                        .WithOne("State")
                        .HasForeignKey("LumiHome.API.Models.DeviceState", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("LumiHome.API.Models.SecurityEvent", b =>
                {
                    b.HasOne("LumiHome.API.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("LumiHome.API.Models.Device", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("State");
                });

            modelBuilder.Entity("LumiHome.API.Models.Room", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
